### ISSUE TITLE
Корректное ли название функции?

### ISSUE THREAD

**Issue by mr-scrpt** [metatech-university/NodeJS-Pure#24]
Здравствуйте, подскажите пожалуйста, почему функция называется serveStatic, ведь по сути  она ничего не сервает? Ну то есть сервер в ней не создается, дальше по коду, где она используется в классе, мы ее кладем в метод `this.staticHandler = serveStatic(staticPath);`
Возможно эту функцию корректнее назвать staticHandler?
https://github.com/metatech-university/NodeJS-Pure/blob/ac7505c3865a87bc4be98219438b7d4fbfa57692/src/server.js#L89

**Comment by tshemsedinov** [comment]
Она как раз сервает, она отдает статику.
